#!/bin/bash
echo $(printf '%o\n' $(($(echo $WATER|tr 'water' '01234'|sed 's/./& /g'|awk '{for(i=1;i<=NF;i++)r=r*5+$i}END{print r}') + $(echo $STIR|tr 'stir' '0123'|sed 's/./& /g'|awk '{for(i=1;i<=NF;i++)r=r*4+$i}END{print r}'))) | tr '01234567' 'bestchol')
