#!/bin/bash
w=$(echo "$WATER"|sed 's/./& /g'|tr 'water' '01234'|awk '{for(i=1;i<=NF;i++)r=r*5+$i}END{print r}');s=$(echo "$STIR"|sed 's/./& /g'|tr 'stir.' '01234'|awk '{for(i=1;i<=NF;i++)r=r*5+$i}END{print r}');printf '%o\n' $((w+s))|tr '01234567' 'bestchol'
